replicaCount: 3

app:
  labels:
    app: "bakehouse"
    env: "production"

image:
  repository: pharogrammer
  name: bakehouse
  version: 35

service:
  type: LoadBalancer
  targetPort: 80
  port: 80
