replicaCount: 3

app:
  labels:
    app: "bakehouse"
    env: "production"

image:
  repository: pharogrammer
  name: bakhouse
  version:  32

service:
  type: LoadBalancer
  targetPort: 80
  port: 80
